### ISSUE TITLE
Browser Testing - Disable Images

### ISSUE THREAD

**Issue by char1129** [tuck0066/web-design-2-independent-project#1]
There you are Keri!

Cute idea for a website! Animals are always a win!
You added an alt tag for your picture on the main page which is great! Remember to add them to the rest of the images as well.
I've also been suggesting that a background colour is added as a placeholder for images just in case they don't load. This may avoid site squishing as well.

Good luck with the rest of the semester!!

Sarah

**Comment by tuck0066** [comment]
Hi Sarah!  

It never wrote me a message that said you responded on here.  TY for the response!  I am still plugging away at it,  I'll do the place holder.  :)  TY
